/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Business.GestaoFabrica.ConfiguraFacil;

/**
 *
 * @author PC - Luis
 */
public class DetalhesGUI extends javax.swing.JFrame {

    private ConfiguraFacil configurafacil;
    /**
     * Creates new form DetalhesGUI
     */
    public DetalhesGUI(ConfiguraFacil configurafacil) {
        initComponents();
        this.configurafacil=configurafacil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonEstofos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ButtonLuzes = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel5 = new javax.swing.JLabel();
        ButtonVE = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ButtonPC = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ButtonTeto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ButtonVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Detalhes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Interiores");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estofos.png"))); // NOI18N

        ButtonEstofos.setText("Estofos");
        ButtonEstofos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEstofosActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luzes.png"))); // NOI18N

        ButtonLuzes.setText("Pacote de Luzes");
        ButtonLuzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLuzesActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vidro.png"))); // NOI18N

        ButtonVE.setText("VidrosEscurecidos");
        ButtonVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVEActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/para-choques.png"))); // NOI18N

        ButtonPC.setText("Para-Choques");
        ButtonPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPCActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teto-solar (1).png"))); // NOI18N

        ButtonTeto.setText("Teto de Abrir");
        ButtonTeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTetoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Exterior");

        ButtonVoltar.setText("Voltar");
        ButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ConfiguraFácil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(ButtonEstofos)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonLuzes)
                                    .addComponent(jLabel3))
                                .addGap(116, 116, 116))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonTeto)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonVoltar)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(ButtonVE)
                                .addGap(82, 82, 82)
                                .addComponent(ButtonPC))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(219, 219, 219)
                .addComponent(jLabel8))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(ButtonEstofos))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(ButtonLuzes)))
                    .addGap(71, 71, 71)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(ButtonTeto))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ButtonVE)
                                .addComponent(ButtonPC))))
                    .addGap(45, 45, 45)
                    .addComponent(ButtonVoltar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEstofosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEstofosActionPerformed
        // TODO add your handling code here:
        dispose();
        EstofoGUI menuestofos = new EstofoGUI(this.configurafacil);
        menuestofos.setVisible(true);
    }//GEN-LAST:event_ButtonEstofosActionPerformed

    private void ButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuConfiguracaoGUI menuConfiguracao = new MenuConfiguracaoGUI(this.configurafacil);
        menuConfiguracao.setVisible(true);
    }//GEN-LAST:event_ButtonVoltarActionPerformed

    private void ButtonLuzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLuzesActionPerformed
        // TODO add your handling code here:
        dispose();
        PacoteLuzesGUI menu = new PacoteLuzesGUI (this.configurafacil);
        menu.setVisible(true);
    }//GEN-LAST:event_ButtonLuzesActionPerformed

    private void ButtonVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVEActionPerformed
        // TODO add your handling code here:
        // Vidros escurecidos
        this.configurafacil.adicionarComponente("Vidros Escurecidos");
        
    }//GEN-LAST:event_ButtonVEActionPerformed

    private void ButtonTetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTetoActionPerformed
        // TODO add your handling code here:
        // teto de abrir
        this.configurafacil.adicionarComponente("Teto de Abrir");
    }//GEN-LAST:event_ButtonTetoActionPerformed

    private void ButtonPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPCActionPerformed
        // TODO add your handling code here:
        dispose();
        ParaChoquesGUI menu = new ParaChoquesGUI(this.configurafacil);
        menu.setVisible(true);
    }//GEN-LAST:event_ButtonPCActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEstofos;
    private javax.swing.JButton ButtonLuzes;
    private javax.swing.JButton ButtonPC;
    private javax.swing.JButton ButtonTeto;
    private javax.swing.JButton ButtonVE;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
