/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Business.GestaoFabrica.ConfiguraFacil;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PC - Luis
 */
public class MenuFabricaGUI extends javax.swing.JFrame {
    
 private ConfiguraFacil configurafacil;
    /**
     * Creates new form PaginaFabrica
     */
    public MenuFabricaGUI(ConfiguraFacil configurafacil) {
        initComponents();
        this.configurafacil=configurafacil;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        VerEncomendas = new javax.swing.JButton();
        VerFuncionarios = new javax.swing.JButton();
        VerStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PáginaFábrica");

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        VerEncomendas.setText("Encomendas");
        VerEncomendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VerEncomendas.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        VerEncomendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEncomendasActionPerformed(evt);
            }
        });

        VerFuncionarios.setText("Funcionarios");
        VerFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerFuncionariosActionPerformed(evt);
            }
        });

        VerStock.setText("Stock");
        VerStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Voltar)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(VerEncomendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(122, 122, 122)
                .addComponent(VerFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(VerStock)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerEncomendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VerFuncionarios)
                    .addComponent(VerStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(Voltar)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerEncomendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEncomendasActionPerformed
         EncomendasGUI encomendas= new EncomendasGUI(this,true,this.configurafacil);
         encomendas.setVisible(true);
    }//GEN-LAST:event_VerEncomendasActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
      this.setVisible(false);
       MenuGestorGUI menugestor= new MenuGestorGUI(this.configurafacil); // abre o menu do gestor
         menugestor.setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void VerFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerFuncionariosActionPerformed
        // TODO add your handling code here:
        dispose();
        VerFuncionariosGUI verfuncionarios= new VerFuncionariosGUI(this,true,this.configurafacil);
            verfuncionarios.setVisible(true);

        
    }//GEN-LAST:event_VerFuncionariosActionPerformed

    private void VerStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerStockActionPerformed
     try {
         // TODO add your handling code here:
         dispose();
         StockGUI stock = new StockGUI (this,true,this.configurafacil);
         stock.setVisible(true);
     } catch (SQLException ex) {
         Logger.getLogger(MenuFabricaGUI.class.getName()).log(Level.SEVERE, null, ex);
     }
            
      
    }//GEN-LAST:event_VerStockActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VerEncomendas;
    private javax.swing.JButton VerFuncionarios;
    private javax.swing.JButton VerStock;
    private javax.swing.JButton Voltar;
    // End of variables declaration//GEN-END:variables
}
