/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Business.GestaoFabrica.Componente;
import Business.GestaoFabrica.ConfiguraFacil;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 *
 * @author PC - Luis
 */
public class PacoteLuzesGUI extends javax.swing.JFrame {

    private ConfiguraFacil configurafacil;
    /**
     * Creates new form PacoteLuzesGUI
     */
    public PacoteLuzesGUI(ConfiguraFacil configurafacil) {
        initComponents();
        this.configurafacil=configurafacil;
        insertPreco();
    }
    
     public void insertPreco(){
       List<Componente> luzes = this.configurafacil.getGestao_fabrica().getLuzes();
       jRadioButtonM1.setText(luzes.get(0).getNome());
       jRadioButtonM2.setText(luzes.get(1).getNome());
       jRadioButtonM3.setText(luzes.get(2).getNome());
       jRadioButtonM4.setText(luzes.get(2).getNome());
       Preco1.setText(String.valueOf(luzes.get(0).getPreco()));
       Preco2.setText(String.valueOf(luzes.get(1).getPreco()));
       Preco3.setText(String.valueOf(luzes.get(2).getPreco()));
       preco4.setText(String.valueOf(luzes.get(2).getPreco()));
     }
    
    
   public String RadioButtonSelected(){
        String componente="";
         Enumeration elements = buttonGroup1.getElements();
     while (elements.hasMoreElements()) {
        JRadioButton button = (JRadioButton)elements.nextElement();
        if (button.isSelected()) {
             if(buttonGroup1.getSelection().equals(button.getModel()))
                    componente= button.getText();
             return componente;
      }
        
    }
     return componente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonM1 = new javax.swing.JRadioButton();
        jRadioButtonM2 = new javax.swing.JRadioButton();
        jRadioButtonM3 = new javax.swing.JRadioButton();
        jRadioButtonM4 = new javax.swing.JRadioButton();
        jButtonContinuar = new javax.swing.JButton();
        Preco1 = new javax.swing.JLabel();
        Preco2 = new javax.swing.JLabel();
        Preco3 = new javax.swing.JLabel();
        preco4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setTitle("Pacote de Luzes");

        buttonGroup1.add(jRadioButtonM1);
        jRadioButtonM1.setSelected(true);
        jRadioButtonM1.setText("Luzes LED");

        buttonGroup1.add(jRadioButtonM2);
        jRadioButtonM2.setText("Luzes Neon");

        buttonGroup1.add(jRadioButtonM3);
        jRadioButtonM3.setText("Luzes Halógenas ");

        buttonGroup1.add(jRadioButtonM4);
        jRadioButtonM4.setText("Luzes Fluorescentes");

        jButtonContinuar.setText("Continuar");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        Preco1.setText("jLabel1");

        Preco2.setText("jLabel2");

        Preco3.setText("jLabel3");

        preco4.setText("jLabel4");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonContinuar)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonM4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(preco4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonM3)
                                .addGap(18, 18, 18)
                                .addComponent(Preco3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonM1)
                                    .addComponent(jRadioButtonM2))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Preco2)
                                    .addComponent(Preco1))))
                        .addContainerGap(59, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonM1)
                    .addComponent(Preco1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonM2)
                    .addComponent(Preco2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonM3)
                    .addComponent(Preco3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonM4)
                    .addComponent(preco4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContinuar)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        // TODO add your handling code here:
        //continuar
       String comp = RadioButtonSelected();
        List<String> incompativeis= this.configurafacil.getComponenteIncompativeis(comp);
        List<String> obrigatorios= this.configurafacil.compObrigatorios(comp);
            if(obrigatorios.size()!=1){
                DependenciasGUI aviso= new DependenciasGUI(this,true,this.configurafacil,obrigatorios);
                aviso.setVisible(true);
            }
            if(incompativeis.size()!=1){
                IncompativelGUI aviso = new IncompativelGUI(this,true,this.configurafacil,incompativeis);
                aviso.setVisible(true);
            }
            else {this.configurafacil.adicionarComponente(comp);}

            dispose();

      DetalhesGUI menu = new DetalhesGUI(this.configurafacil);
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //voltar
        dispose();
        DetalhesGUI menu = new DetalhesGUI(this.configurafacil);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Preco1;
    private javax.swing.JLabel Preco2;
    private javax.swing.JLabel Preco3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonM1;
    private javax.swing.JRadioButton jRadioButtonM2;
    private javax.swing.JRadioButton jRadioButtonM3;
    private javax.swing.JRadioButton jRadioButtonM4;
    private javax.swing.JLabel preco4;
    // End of variables declaration//GEN-END:variables
}
