/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author PC - Luis
 */
public class PaginaFabricaGUI extends javax.swing.JFrame {
    

    /**
     * Creates new form PaginaFabrica
     */
    public PaginaFabricaGUI() {
        initComponents();
    }
     public void close() {
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoutFuncionario = new javax.swing.JButton();
        VerEncomendas = new javax.swing.JButton();
        VerFuncionarios = new javax.swing.JButton();
        VerStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PáginaFábrica");

        LogoutFuncionario.setText("Logout");
        LogoutFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutFuncionarioActionPerformed(evt);
            }
        });

        VerEncomendas.setText("Encomendas");
        VerEncomendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VerEncomendas.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        VerEncomendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEncomendasActionPerformed(evt);
            }
        });

        VerFuncionarios.setText("Funcionarios");
        VerFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerFuncionariosActionPerformed(evt);
            }
        });

        VerStock.setText("Stock");
        VerStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutFuncionario)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(VerEncomendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(122, 122, 122)
                .addComponent(VerFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(VerStock)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerEncomendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VerFuncionarios)
                    .addComponent(VerStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(LogoutFuncionario)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerEncomendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEncomendasActionPerformed
         
    }//GEN-LAST:event_VerEncomendasActionPerformed

    private void LogoutFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutFuncionarioActionPerformed
       
    }//GEN-LAST:event_LogoutFuncionarioActionPerformed

    private void VerFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerFuncionariosActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_VerFuncionariosActionPerformed

    private void VerStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerStockActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_VerStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaFabricaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaFabricaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaFabricaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaFabricaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaFabricaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutFuncionario;
    private javax.swing.JButton VerEncomendas;
    private javax.swing.JButton VerFuncionarios;
    private javax.swing.JButton VerStock;
    // End of variables declaration//GEN-END:variables
}
