/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Business.GestaoFabrica.Componente;
import Business.GestaoFabrica.ConfiguraFacil;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 *
 * @author PC - Luis
 */
public class ParaChoquesGUI extends javax.swing.JFrame {

    private ConfiguraFacil configurafacil;
    /**
     * Creates new form ParaChoquesGUI
     */
    public ParaChoquesGUI(ConfiguraFacil configurafacil) {
        initComponents();
        this.configurafacil=configurafacil;
        insertPreco();
    }
   public void insertPreco(){
       List<Componente> pc = this.configurafacil.getGestao_fabrica().getParachoques();
       jRadioButtonM1.setText(pc.get(0).getNome());
       jRadioButtonM2.setText(pc.get(1).getNome());
       jRadioButtonM3.setText(pc.get(2).getNome());
       jRadioButtonM4.setText(pc.get(3).getNome());
       Preco1.setText(String.valueOf(pc.get(0).getPreco()));
       Preco2.setText(String.valueOf(pc.get(1).getPreco()));
       Preco3.setText(String.valueOf(pc.get(2).getPreco()));
       Preco4.setText(String.valueOf(pc.get(3).getPreco()));
     }
    
    
    
    
    public String RadioButtonSelected(){
        String componente="";
         Enumeration elements = buttonGroup1.getElements();
     while (elements.hasMoreElements()) {
        JRadioButton button = (JRadioButton)elements.nextElement();
        if (button.isSelected()) {
             if(buttonGroup1.getSelection().equals(button.getModel()))
                    componente= button.getText();
             return componente;
      }
        
    }
     return componente;
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonM1 = new javax.swing.JRadioButton();
        Preco1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonM2 = new javax.swing.JRadioButton();
        Preco2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonM3 = new javax.swing.JRadioButton();
        Preco3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonM4 = new javax.swing.JRadioButton();
        Preco4 = new javax.swing.JLabel();
        jButtonContinuar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/parachoque1.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonM1);
        jRadioButtonM1.setSelected(true);
        jRadioButtonM1.setText("Modelo 1");

        Preco1.setText("Preco1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/parachoque2.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonM2);
        jRadioButtonM2.setText("Modelo 2");

        Preco2.setText("Preco 2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/parachoque3.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonM3);
        jRadioButtonM3.setText("Modelo 3");

        Preco3.setText("Preco3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/parachoque4.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonM4);
        jRadioButtonM4.setText("Modelo 4");

        Preco4.setText("Preco4");

        jButtonContinuar.setText("Continuar");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonM1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Preco1)))
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Preco2))
                            .addComponent(jRadioButtonM2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonM3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Preco3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonM4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Preco4))
                            .addComponent(jButton1))
                        .addGap(35, 35, 35)))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonContinuar)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonM1)
                    .addComponent(jRadioButtonM2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Preco1)
                    .addComponent(Preco2))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonM3)
                    .addComponent(jRadioButtonM4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Preco3)
                    .addComponent(Preco4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContinuar)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // voltar
        dispose();
        DetalhesGUI menu = new DetalhesGUI(this.configurafacil);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed

       String comp = RadioButtonSelected();
        List<String> incompativeis= this.configurafacil.getComponenteIncompativeis(comp);
        List<String> obrigatorios= this.configurafacil.compObrigatorios(comp);
            if(obrigatorios.size()!=1){
                DependenciasGUI aviso= new DependenciasGUI(this,true,this.configurafacil,obrigatorios);
                aviso.setVisible(true);
            }
            if(incompativeis.size()!=1){
                IncompativelGUI aviso = new IncompativelGUI(this,true,this.configurafacil,incompativeis);
                aviso.setVisible(true);
            }
            else {this.configurafacil.adicionarComponente(comp);}

            dispose();


      DetalhesGUI menu = new DetalhesGUI(this.configurafacil);
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Preco1;
    private javax.swing.JLabel Preco2;
    private javax.swing.JLabel Preco3;
    private javax.swing.JLabel Preco4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonM1;
    private javax.swing.JRadioButton jRadioButtonM2;
    private javax.swing.JRadioButton jRadioButtonM3;
    private javax.swing.JRadioButton jRadioButtonM4;
    // End of variables declaration//GEN-END:variables
}
